name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:testing
    steps:
    - uses: actions/checkout@v3

    - name: Install Build Dependencies
      run: |
        apt-get -yqq update && apt-get -yqq --no-install-recommends install build-essential meson ninja-build libgtk-3-0 libgtk-3-dev libgladeui-dev gtk-doc-tools libgirepository1.0-dev

    - name: Build
      run: |
        meson setup build
        ninja -C  build

    - uses: actions/upload-artifact@v3
      with:
        name: app
        path: ./build/gtksheet/testgtksheet